import {
  Utensils,
  Car,
  Home,
  Gamepad2,
  HeartPulse,
  GraduationCap,
  Ellipsis,
  ShoppingBag,
  Coffee,
  Plane,
  Music,
  Book,
  Gift,
  Phone,
  Wifi,
  Shirt,
  Scissors,
  Dumbbell,
  Baby,
  Dog,
  Briefcase,
  PiggyBank,
  CreditCard,
  Fuel,
  Bus,
  Clapperboard,
  Pill,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  home: Home,
  "gamepad-2": Gamepad2,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  ellipsis: Ellipsis,
  "shopping-bag": ShoppingBag,
  coffee: Coffee,
  plane: Plane,
  music: Music,
  book: Book,
  gift: Gift,
  phone: Phone,
  wifi: Wifi,
  shirt: Shirt,
  scissors: Scissors,
  dumbbell: Dumbbell,
  baby: Baby,
  dog: Dog,
  briefcase: Briefcase,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  fuel: Fuel,
  bus: Bus,
  clapperboard: Clapperboard,
  pill: Pill,
  wrench: Wrench,
};

export const ICON_OPTIONS = Object.keys(ICON_MAP);

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] || Ellipsis;
}
